version: '3.8'

services:
  app:
    build: ./app
    container_name: usage-tracker
    ports:
      - "8080:8080"
    depends_on:
      assessment:
        condition: service_started
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/v1/dataset"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
  assessment:
    image: mrksdh/assessment
    ports:
      - "8888:8080"